-- Align NOT NULL updatedAt columns with Prisma @updatedAt (default on insert).
ALTER TABLE "Source" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Kirtan" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "KirtanText" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "KirtanAudio" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Collection" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
